Makefile, docs/development.md, examples/manifests/consumer.yaml, examples/manifests/hw-event-proxy.yaml, examples/manifests/kustomization.yaml, examples/manifests/namespace.yaml, examples/manifests/roles.yaml, examples/manifests/route.yaml, examples/manifests/secret.yaml, examples/manifests/service-account.yaml, examples/manifests/service.yaml, hw-event-proxy/Makefile, hw-event-proxy/cmd/main.go, hw-event-proxy/util/util.go, message-parser/server.py
Added cluster deployment yaml files.
Added Makefile for cluser deployment.
Added env MSG_PARSER_TIMEOUT for customizing message parser timeout.
Added secret for Redfish basic auth.
=> Hw-event-proxy cluster deployment

hw-event-proxy/cmd/main.go
Also add a trace log for webhook to help with developer tests.
=> Update logs to show Marshaling error

.github/workflows/hw-event-proxy.yaml, README.md, e2e-tests/scripts/test.sh
=> update readme and performance check

e2e-tests/scripts/verify-basic.py
=> fix verify-basic python syntax

e2e-tests/scripts/verify-basic.py
=> python3.6 compliance

CONTRIBUTING.md, README.md, docs/development.md
=> Update README and contribution pages

Dockerfile.dev, Dockerfile.docker, e2e-tests/scripts/test.sh
=> Add Dockerfile for quay.io ci build

Dockerfile.dev, scripts/build-go.sh
=> GO111MODULE=on

Dockerfile.dev
=> remove GOFLAGS

Dockerfile.dev
=> use quay.io for golang builder

Dockerfile.dev
=> fix image name

docs/development.md
=> update docs for e2e tests

Dockerfile
=> update builder to golang-1.17

hw-event-proxy/go.mod, hw-event-proxy/go.sum, hw-event-proxy/vendor/modules.txt
=> update sdk-go to go 1.17

e2e-tests/scripts/test.sh
=> Display imageID used for testing

scripts/build-go.sh
=> update build scripts

e2e-tests/scripts/test.sh
=> temp add check_images

e2e-tests/scripts/test.sh
=> display containers info

e2e-tests/scripts/test.sh
=> minor update of test log

e2e-tests/scripts/test.sh
=> comment out debug logs

scripts/entrypoint.sh
=> Pass api-port to entrypoint.sh

Makefile, manifests/base/consumer.yaml, manifests/base/hw-event-proxy.yaml
=> update image location to quay.io/redhat-cne

hw-event-proxy/cmd/main.go, message-parser/requirements.txt, message-parser/server.py
=> Lock dependence with sushy 4.0.0

e2e-tests/data/Multiple-EventRecords.json, e2e-tests/data/README.md, e2e-tests/data/iLOEvents.0.9.PowerSupplyRemoved.json, hw-event-proxy/go.mod, hw-event-proxy/go.sum, hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event_marshal.go, hw-event-proxy/vendor/modules.txt
=> Update Redfish schema and add e2e tests

README.md
=> Update subscription CRD in doc

message-parser/setup.cfg
Added setup.cfg to define package metadata for the cachito build.
Signed-off-by: Don Penney <dpenney@redhat.com>
=> Add setup.cfg to message-parser

hw-event-proxy/go.mod, hw-event-proxy/go.sum, hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go, hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/v1/event/event.go, hw-event-proxy/vendor/modules.txt
=> Update sdk-go modules

Dockerfile.art, message-parser/requirements.txt
Signed-off-by: Don Penney <dpenney@redhat.com>
=> Add Dockerfile.art build file

Dockerfile.art
test build https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46119159
=> update docker file to reconcile with art

README.md, docs/development.md, hw-event-proxy/go.mod, hw-event-proxy/go.sum, hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/v1/event/event.go, hw-event-proxy/vendor/modules.txt, manifests/consumer/kustomization.yaml, manifests/proxy/kustomization.yaml
=> minor update sdk-go

Dockerfile, Dockerfile.dev, Dockerfile.local, Makefile, README.md, hw-event-proxy/cmd/main.go, hw-event-proxy/go.mod, hw-event-proxy/go.sum, hw-event-proxy/vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go, hw-event-proxy/vendor/modules.txt, manifests/consumer/deployment.yaml, manifests/consumer/kustomization.yaml, manifests/proxy/deployment.yaml, manifests/proxy/kustomization.yaml
=> Upgrade to golang 1.18 and update sdk-go

message-parser-cachito/requirements.in, message-parser-cachito/requirements.txt, message-parser/requirements.txt
=> Upgrade protobuf to 3.20.2 for message-parser

docs/development.md, manifests/proxy/kustomization.yaml
=> remove private info

README.md, hw-event-proxy/cmd/main.go, manifests/consumer/deployment.yaml
Adds the o in front of cloudNotifications URI
OCPBUGS-7441
=> BUG OCPBUGS-7441: Match the O-RAN specification for the ocloudNotifications URI

Makefile, docs/development.md, manifests/layers/proxy-pvc/kustomization.yaml, manifests/layers/proxy-pvc/pvc.yaml, manifests/layers/proxy-pvc/update-pvc.yaml, manifests/pv/kustomization.yaml, manifests/pv/lv.yaml, manifests/pv/pv.yaml, manifests/pv/storage-class.yaml
=> configure persistent storage for event producer

Makefile, e2e-tests/scripts/test.sh, e2e-tests/scripts/verify-sanity.py, manifests/consumer/kustomization.yaml, manifests/proxy/kustomization.yaml
fix test script.
use example ip address from https://datatracker.ietf.org/doc/html/rfc5737.
=> fix e2e test script
